version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
      - ./index.html:/app/index.html
      - ./webpack.config.js:/app/webpack.config.js
      - ./package.json:/app/package.json
      - ./.babelrc:/app/.babelrc
      - ./.babelrc:/app/.babel.config.js